log:
  level: INFO

api:
  insecure: false # Don't do that in production
  dashboard: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'

  websocket:
    address: ':8072'


certificatesResolvers:
  letsencrypt:
    acme:
      email: 'akhamissi@gmail.com'
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web


http:
  routers:
    web-secure-router:
      rule: "Host(`yancrm.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: web
      tls:
        certResolver: letsencrypt

    traefik-dashboard:
      rule: "Host(`yancrm.com`) && (PathPrefix(`/traefik`) || PathPrefix(`/dashboard`))"
      service: api@internal
      middlewares:
        - auth 
      entryPoints:
        - web-secure
      tls: 
        certResolver: letsencrypt

    odoo-websocket:
      rule: "Host(`yancrm.com`) && Path(`/longpolling`)"
      service: odoo
      entryPoints:
        - websocket

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']
    auth:
      basicAuth:
        users:
          - "testuser:$apr1$jIKW.bdS$eKXe4Lxjgy/rH65wP1iQe1" # Use the hashed password for the user


  services:
    odoo:
      loadBalancer:
        servers:
          - url: http://odoo:8069


providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
