[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false

[http]
  [http.routers.odoo-ws]
    rule = "Host(`odoo.localhost`) && Path(`/websocket`)"
    service = "odoo-ws"
    entryPoints = ["websecure"]

  [http.services.odoo-ws.loadBalancer]
    [[http.services.odoo-ws.loadBalancer.servers]]
      url = "http://odoo:8072"  #

[certificatesResolvers.letsencrypt.acme]
email = "akhamissi@gmail.com"
storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web" # Use the 'web' entry point for HTTP challenges

[http.middlewares]
  [http.middlewares.odoo-https-redirect.redirectScheme]
    scheme = "https"

[[tls.certificates]]
  certFile = "/letsencrypt/cert.crt"
  keyFile = "/letsencrypt/private.key"
